project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Election Data Analysis"
  author:
    - Daphne Manning (djm2266)
    - Jie Hu (jh4741)
  repo-url: https://github.com/djm2266/electionData.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


